### ISSUE TITLE
please ask the problem that for this driver what is xilinx project about AXI-stream FIFO?

### ISSUE THREAD

**Issue by zhang007z** [jacobfeder/axisfifo#12]
hi jacobfeder
if you have this dialog block of xilinx AXI-stream FIFO project,please send it to me.in this way I can learn to drive against xilinx AXI-stream FIFO project.
thank you.

**Comment by jacobfeder** [comment]
Hi @zhang007z , I don't have a picture, but you can use the automated connection wizard. You also need to be sure to connect the interrupt lines to the zynq processor.

**Comment by zhang007z** [comment]
can you help me to create xilinx AXI-stream FIFO project for your driver? thank you advance.
