### ISSUE TITLE
axis_fifo is not found under /dev

### ISSUE THREAD

**Issue by nardhini** [jacobfeder/axisfifo#2]
Hi @jacobfeder ,
I am trying to create an application using PetaLinux which uses AXIS Stream FIFO. I had created a module and put the axis-fifo.c file under it and created an application and put the fifo-test.c file under it. After building and booting the system image on Zynq board, the axis_fifo device was not found under /dev folder. I am not sure what I am missing in the entire proceduer. Could you please help fix the problem?

**Comment by jacobfeder** [comment]
Hi @nardhini , please send your pl.dtsi (<petalinux project>/components/plnx_workspace/device-tree/device-tree/pl.dtsi) and the output of dmesg after booting.

**Comment by nardhini** [comment]
Hi @jacobfeder 
[attachment.zip](https://github.com/jacobfeder/axisfifo/files/2331926/attachment.zip)
PFA the pl.dtsi file and dmesg output.

**Comment by nardhini** [comment]
Hi @jacobfeder ,
Did you get a chance to go through the files I sent?

**Comment by jacobfeder** [comment]
Hi @nardhini  sorry about the delay. Notice in the dmesg output:
`axis_fifo 43c00000.axi_fifo_mm_s: no IRQ found for 0x0x43c00000
axis_fifo: probe of 43c00000.axi_fifo_mm_s failed with error -5`
It looks like you didn't hook up the FIFO's interrupt line to the zynq. Let me know if that doesn't fix it.

Cheers

**Comment by zhang007z** [comment]
at sametime I want to know that in your code how to  determine AXI_Stream_FIFO base address?
when do you assign this base address? when do you make linux kernel?

**Comment by jacobfeder** [comment]
![screenshot from 2018-12-25 20-38-44](https://user-images.githubusercontent.com/4839669/50431051-1ce5b700-0885-11e9-8692-e6d5efb62665.png)
Highlighted orange line is the interrupt line which must be connected to the Zynq.

The base address of the IP will be listed in the linux device tree files (probably pl.dtsi as discussed above).

**Comment by zhang007z** [comment]
Hi Jacobfeder
please can your axi_stream_fifo be created several instantiations? In other words,if I use Vivado tool to create several axi_stream_fifo ,can your driver recognition these axi_stream_fifo of zynq ? If it can recognition ,in vivado How to design block?another in block design How to connect the interrupt to zynq? How does This driver handle these interrupt?I am newbie,can you detailed say this procedure?thanks in advance.

**Comment by jacobfeder** [comment]
Hi @zhang007z , the driver does support multiple axis fifos. Use the "connection automation" button in the block design to automatically make the AXI connections. A sort of confusing fact about Zynq interrupts is that if you need to connect multiple you must use a "concat" block as shown in this link:
https://forums.xilinx.com/t5/Embedded-Processor-System-Design/Multiple-interrupts-response-from-PL-to-PS/td-p/808478

**Comment by zhang007z** [comment]
Additionally，I have one question, how does your driver find corresponding axi_stream_fifo device of zynq board?the driver find device by major and sub device number?I confuse that how do your driver find axi_stream_fifo device of zynq board?

**Comment by jacobfeder** [comment]
The major/minor device numbers are assigned automatically by the linux kernel. The devices are found by the linux kernel in the device tree. If you look up embedded linux device trees you will find more info on how that works.

**Comment by 4sRanch** [comment]
@jacobfeder 
I am using 2024.1 petalinux sdk and trying to build axis-fifo driver after enabling the config under staging drivers. My build is successful but the driver is not present in lib/modules. Also no corresponding filename under /dev on the board. The dtsi setting is shown below. As someone suggested on the forum  tried system-user.dtsi with  compatible version string. Didn't help. Appreciate your help.
amba_pl: pl-bus {
		#address-cells = <2>;
		#size-cells = <2>;
		compatible = "simple-bus";
		ranges ;
		axi_fifo_mm_s_0: axi_fifo_mm_s@a0010000 {
			clock-names = "s_axi_aclk";
			clocks = <&zynqmp_clk 71>;
			compatible = "xlnx,axi-fifo-mm-s-4.3";
			reg = <0x0 0xa0010000 0x0 0x10000>;
			xlnx,axi-str-rxd-protocol = "XIL_AXI_STREAM_ETH_DATA";
			xlnx,axi-str-rxd-tdata-width = <0x20>;
			xlnx,axi-str-txc-protocol = "XIL_AXI_STREAM_ETH_CTRL";
			xlnx,axi-str-txc-tdata-width = <0x20>;
			xlnx,axi-str-txd-protocol = "XIL_AXI_STREAM_ETH_DATA";
			xlnx,axi-str-txd-tdata-width = <0x20>;
			xlnx,axis-tdest-width = <0x4>;
			xlnx,axis-tid-width = <0x4>;
			xlnx,axis-tuser-width = <0x4>;
			xlnx,data-interface-type = <0x0>;
			xlnx,has-axis-tdest = <0x0>;
			xlnx,has-axis-tid = <0x0>;
			xlnx,has-axis-tkeep = <0x0>;
			xlnx,has-axis-tstrb = <0x0>;
			xlnx,has-axis-tuser = <0x0>;
			xlnx,rx-cascade-height = <0x0>;
			xlnx,rx-enable-ecc = <0x0>;
			xlnx,rx-fifo-depth = <0x200>;
			xlnx,rx-fifo-pe-threshold = <0x5>;
			xlnx,rx-fifo-pf-threshold = <0x1fb>;
			xlnx,rx-has-ecc-err-inject = <0x0>;
			xlnx,s-axi-id-width = <0x4>;
			xlnx,s-axi4-data-width = <0x20>;
			xlnx,select-xpm = <0x0>;
			xlnx,tx-cascade-height = <0x0>;
			xlnx,tx-enable-ecc = <0x0>;
			xlnx,tx-fifo-depth = <0x200>;
			xlnx,tx-fifo-pe-threshold = <0x5>;
			xlnx,tx-fifo-pf-threshold = <0x1fb>;
			xlnx,tx-has-ecc-err-inject = <0x0>;
			xlnx,use-rx-cut-through = <0x0>;
			xlnx,use-rx-data = <0x1>;
			xlnx,use-tx-ctrl = <0x1>;
			xlnx,use-tx-cut-through = <0x0>;
			xlnx,use-tx-data = <0x1>;
		};
