### ISSUE TITLE
README.md quick test instructions clarification?

### ISSUE THREAD

**Issue by sarenameas** [jacobfeder/axisfifo#20]
In the README.md in the home page you have these instructions to quickly test.

>To quickly test things, you can write a packet to your fifo from the command line with
echo -n -e '\xDE\xAD\xBE\xEF' > /dev/axis_fifo<#>
and read from it with
cat /dev/axis_fifo<#> | hexdump -C.

I want to clarify, if our axis-fifo is wired in hardware for loopback, we won't get data when we cat, correct?

Thank you!

**Comment by jacobfeder** [comment]
If your axis-fifo is wired for loopback you SHOULD get data if you wrote a packet like in the previous line using echo.
