### ISSUE TITLE
Problem with 2 AXi FIFOs

### ISSUE THREAD

**Issue by ivisha** [jacobfeder/axisfifo#21]
Hi!
I am using Zynq7020 based design and have Ubuntu 20.4 rootfs with Petalinux 2020.2 kernel on one ARM cortex, and I have run the last version of the axis-fifo driver. 

On the PL side I have 2 AXI-Stream FIFOs (v4.2): 
- one connected only to read data from PL (DB FIFO) which is periodically being written to from the PL:
    Data Interface : AXI4 Lite
    Enabled check-boxes: Enable Receive Data, TDEST Width 4
    Receive Fifo Depth 512
    Full Threshold 507
    Empty Threshold 5

- the other connected to write to/read from PL, with the loopback implemented on PL:
    Data Interface : AXI4 Lite
    Enabled check-boxes: Enable Transmit/Receive Data, TDEST Width 4
    Transmit/Receive Fifo Depth 512
    Full Threshold 507
    Empty Threshold 5

In addition, in the driver code I commented the lines related to checking tdest, tx-max-pkt-size and rx-min-pkt-size.

Both AXI FIFOs are created correctly:
```
axis_fifo 40001000.axi_fifo_mm_s: axis-fifo created at 0x40001000 mapped to 0x0xf080a000, irq=54, major=241, minor=0
axis_fifo 40000000.axi_fifo_mm_s: axis-fifo created at 0x40000000 mapped to 0x0xf080c000, irq=55, major=240, minor=0
```

I have made two examples: 
- **fifo_read** to read data from DB FIFO, and 
- **fifo_rw_loop** based on axis-fifo-echo-test.c for ARM FIFO.

When both examples are running everything is working ok. But when the **fifo_read** is stopped (or not run at all), as soon as the DB FIFO becomes full, the **fifo_rw_loop** keeps getting ARM FIFO empty, i.e. does not read any data from the ARM FIFO while the write process to the ARM FIFO continues to work fine. I tried both BLOCKING (it jumps out with the read timeout for the read_timeout values of 1000ms or 5000ms, but with read_timeout of -1 it stays indefinitely in wait_event_interruptible_lock_irq_timeout) and NON_BLOCKING read with the same results. As soon as I run the **fifo_read** and start reading DB FIFO, everything starts working ok again.

The same happens when I restart the driver (rmmod/insmod) – everything works ok until DB FIFO is detected as full.

How/why does the state of one FIFO affect the (wrong) state of the other FIFO? How are these two instances of the driver related?

**Comment by jacobfeder** [comment]
It's been awhile since I've looked at this code, but here's a guess:
AFAIK the only place where two separate FIFOs would be connected is their interrupt lines. Are you sure you have them connected properly in the vivado block diagram? I remember you need some sort of multiplexing block.

**Comment by ivisha** [comment]
Thank you for your  prompt reply! 

The interrupt lines are connected correctly. However, there is a problem in HW project - in the meantime I made a baremetal app in Vitis, performing the same thing: reading DB FIFO and writing to/reading from ARM FIFO. When I stop/remove DB FIFO read,  ARM FIFO read stops after the same amount of time as in the linux example. So I will have to explore this...

Anyway, the AXI FIFO driver obviously works fine in version 2020.2.

Thank you once again!
