### ISSUE TITLE
unable to change read and write timeout

### ISSUE THREAD

**Issue by lukasnagel98** [jacobfeder/axisfifo#26]
Hi, since the driver is now build in the petalinux kernel, i was unable to run 

> insmod /lib/modules/4.9.0-xilinx-v2017.4/extra/axis-fifo.ko read_timeout=-1 write_timeout=-1

because the axis-fifo.ko is not found. Where can i change these values?

**Comment by jacobfeder** [comment]
I'm not sure of the exact path, but I think the driver should still be somewhere in /lib/modules. Maybe run a search there?

**Comment by lukasnagel98** [comment]
I've found the path where the parameters are stored: 
in 
> /sys/module/axis_fifo/parameters

there are two files called read_timeout  and  write_timeout. They contain the value '1000'.
Petalinx however doesn't allow changes
Searching returns no file named axis-fifo.ko or even axis-fifo.o. The later can be found in build directorry from petalinux


The startup dialog shows this:
```

[    5.068438] axis-fifo driver loaded with parameters read_timeout = 1000, write_timeout = 1000
[    5.076954] axis_fifo a0000000.axi_fifo_mm_s: axis-fifo created at 0x00000000a0000000 mapped to 0x0xffff800012b50000, irq=48, major=243, minor=0

```

**Comment by jacobfeder** [comment]
Sorry, not sure then. If you could find the driver location maybe you could `rmmod` then re-add it with `insmod`

**Comment by lukasnagel98** [comment]
Okay, i've made some progress. Changing the Kernal Configuration from "*" to "M"  modularizes the features. Now i have the right file at 

> /lib/modules/5.4.0/kernel/drivers/staging/axis-fifo/axis-fifo.ko
  
I tried to run the insmod command, but it gives me an error since the driver is runnig since startup.
Running rmod and re-adding it works.

I'm serching for the startup script where linux loads this driver, so i can modify it to allways launch with -1.
