### ISSUE TITLE
Linux Kernel Fails to Associate Driver Under 2018.3 Due to IP Version Number Change

### ISSUE THREAD

**Issue by esorton** [jacobfeder/axisfifo#3]
Xilinx updated the AXI Stream FIFO IP in Vivado 2018.3.  The version number bumped from 4.1 to 4.2.

The change log at https://www.xilinx.com/support/answers/71806.html lists the changes as:

> AXI-Stream FIFO (4.2)
> * Version 4.2
> * Feature Enhancement: FIFO generator replaced with XPM.
> * Feature Enhancement: Default values for FIFO_PE_THRESHOLD parameters changed to 5.
> * Revision change in one or more subcores

**Comment by jacobfeder** [comment]
Could you submit this as a pull request?

Thanks!

**Comment by esorton** [comment]
I will.  Need to do a bit of research to determine the format of the ".compatible" field to support both 4.1 and 4.2 versions.

**Comment by jacobfeder** [comment]
Thanks! Appreciate it.
